-- (floor (floor x)) == (floor x)
--  
-- it is the case if x is integer, because for integer (floor x) == x
--  
-- but sinse (floor x) gives us integer (floor (floor x)) == (floor x) also for all real numbers